version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
     - cd $CODEBUILD_SRC_DIR
     - npm run build
     - cp $CODEBUILD_SRC_DIR/appspec.yml $CODEBUILD_SRC_DIR/dist/
     - cp $CODEBUILD_SRC_DIR/info.php $CODEBUILD_SRC_DIR/dist/
     - cp $CODEBUILD_SRC_DIR/scripts $CODEBUILD_SRC_DIR/dist/
artifacts:
  files:
      - '**/*'
  base-directory: $CODEBUILD_SRC_DIR/dist

