version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - mkdir /tmp/output-dir
  build:
    commands:
     - echo cd $CODEBUILD_SRC_DIR
     - echo npm run build
  post_build:
    commands:
      - rm -rf /tmp/output-dir && mkdir /tmp/output-dir
      - cp -r $CODEBUILD_SRC_DIR/* /tmp/output-dir
artifacts:
  files:
    - '*'
  discard-paths: yes
  base-directory: /tmp/output-dir/
