version: 0.2

phases:
  install:
    commands:
      - npm install
      - apt-get -f install
  pre_build:
    commands:
      - mkdir /tmp/output-dir
  build:
    commands:
     - cd /codebuild/output/src865394398/src/github.com/subhasis-karmakar/buildproject 
     - echo npm run build
  post_build:
    commands:
      - rm -rf /tmp/output-dir && mkdir /tmp/output-dir
      - cp *.zip /tmp/output-dir
artifacts:
  files:
    - '*'
  discard-paths: yes
  base-directory: /tmp/output-dir/
