version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - echo npm run build
  post_build:
    commands:
      - echo cp -r /dist/* /
      - echo rm -rf /dist
